name: CI/CD Release Workflow with Manual Major/Minor Version and Automatic Patch Version Bump

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Bump patch version
        run: uv run invoke bump-version

      - name: Commit and push version bump
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add eero/version.py
          git commit -m "ci: bump patch version [skip ci]"
          git push origin master

      - name: Build & Publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv run invoke release
